image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  IMAGE: registry.gitlab.com/bockiii/deemix-docker
  DOCKER_CLI_EXPERIMENTAL: enabled

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build --pull -f Dockerfile.arm64v8 -t $IMAGE:arm64v8 .
    - docker push $IMAGE:arm64v8
    - docker build --pull -f Dockerfile.arm32v7 -t $IMAGE:armhf .
    - docker push $IMAGE:armhf
    - docker build --pull -t $IMAGE:amd64 .
    - docker push $IMAGE:amd64
    - docker manifest create $IMAGE $IMAGE:amd64 $IMAGE:armhf $IMAGE:arm64v8
    - docker manifest annotate $IMAGE $IMAGE:armhf --os linux --arch arm
    - docker manifest annotate $IMAGE $IMAGE:arm64v8 --os linux --arch arm64
    - docker manifest push $IMAGE